// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs5ZZzCz7NM1NJEuLJSjM5x7IVjdbvJEg',
    appId: '1:583562149:web:548ae1b83e12cf53042e4c',
    messagingSenderId: '583562149',
    projectId: 'test-push-notification-f-c8bba',
    authDomain: 'test-push-notification-f-c8bba.firebaseapp.com',
    storageBucket: 'test-push-notification-f-c8bba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe0itgYyMbIg_o-liaSnRE_f8uY2YlbgY',
    appId: '1:583562149:android:38029ca4d4097719042e4c',
    messagingSenderId: '583562149',
    projectId: 'test-push-notification-f-c8bba',
    storageBucket: 'test-push-notification-f-c8bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfweqQeQgDFw162AqLasdQuFSDu8-KvPw',
    appId: '1:583562149:ios:91cbb2b831eefe42042e4c',
    messagingSenderId: '583562149',
    projectId: 'test-push-notification-f-c8bba',
    storageBucket: 'test-push-notification-f-c8bba.appspot.com',
    iosClientId: '583562149-g099vo8s5h3sd8jb0prsao0gl6gceff2.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfweqQeQgDFw162AqLasdQuFSDu8-KvPw',
    appId: '1:583562149:ios:3851e51ec43f4f3d042e4c',
    messagingSenderId: '583562149',
    projectId: 'test-push-notification-f-c8bba',
    storageBucket: 'test-push-notification-f-c8bba.appspot.com',
    iosClientId: '583562149-4lq9mo7kjt1umego0ssgqe9d0qj0finv.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
